"use client";

import { useEffect, useMemo, useState } from "react";
import { BarChart3, CheckCircle2, Loader2, MousePointerClick, Save, Target } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import { createClient } from "@/lib/supabase/client";
import { useCan } from "@/hooks/use-can";

type Lead = { id: string; name: string | null; phone: string; lead_source: string; utm_campaign: string | null; conversion_status: string; created_at: string };
type Settings = { meta_enabled: boolean; meta_pixel_id: string; meta_token: string; has_meta_token: boolean; google_enabled: boolean; google_customer_id: string; google_conversion_action: string; google_token: string; has_google_token: boolean; conversion_event: string };
const INITIAL: Settings = { meta_enabled: false, meta_pixel_id: "", meta_token: "", has_meta_token: false, google_enabled: false, google_customer_id: "", google_conversion_action: "", google_token: "", has_google_token: false, conversion_event: "qualified_lead" };
const LABELS: Record<string, string> = { meta: "Meta Ads", google: "Google Ads", whatsapp: "WhatsApp", organico: "Orgânico", indicacao: "Indicação", landing_page: "Landing page", manual: "Manual" };

export default function LeadTrackingPage() {
  const canEdit = useCan("edit-settings");
  const [leads, setLeads] = useState<Lead[]>([]);
  const [settings, setSettings] = useState(INITIAL);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  useEffect(() => { Promise.all([
    createClient().from("contacts").select("id,name,phone,lead_source,utm_campaign,conversion_status,created_at").order("created_at", { ascending: false }).limit(200),
    fetch("/api/lead-tracking/settings", { cache: "no-store" }).then(async r => ({ ok: r.ok, body: await r.json().catch(() => ({})) })),
  ]).then(([contactResult, configResult]) => {
    if (contactResult.error) toast.error("Não foi possível carregar os leads"); else setLeads((contactResult.data ?? []) as Lead[]);
    if (configResult.ok && configResult.body.settings) setSettings(s => ({ ...s, ...configResult.body.settings }));
  }).finally(() => setLoading(false)); }, []);
  const grouped = useMemo(() => leads.reduce<Record<string, number>>((acc, lead) => { acc[lead.lead_source || "organico"] = (acc[lead.lead_source || "organico"] || 0) + 1; return acc; }, {}), [leads]);
  const converted = leads.filter(l => l.conversion_status !== "lead").length;
  const set = <K extends keyof Settings>(key: K, value: Settings[K]) => setSettings(s => ({ ...s, [key]: value }));
  async function convert(contactId: string, status: string) { const response = await fetch("/api/lead-tracking/convert", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ contact_id: contactId, status }) }); const body = await response.json().catch(() => ({})); if (!response.ok) return toast.error(body.error ?? "Falha ao registrar conversão"); setLeads(items => items.map(item => item.id === contactId ? { ...item, conversion_status: status } : item)); toast.success(body.meta === "sent" ? "Conversão salva e enviada à Meta" : "Conversão salva no CRM"); }
  async function save() { setSaving(true); try { const response = await fetch("/api/lead-tracking/settings", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify(settings) }); const body = await response.json().catch(() => ({})); if (!response.ok) return toast.error(body.error ?? "Falha ao salvar"); setSettings(s => ({ ...s, meta_token: "", google_token: "", has_meta_token: s.has_meta_token || !!s.meta_token, has_google_token: s.has_google_token || !!s.google_token })); toast.success("Tracking salvo"); } catch { toast.error("Falha de conexão"); } finally { setSaving(false); } }
  if (loading) return <div className="flex h-64 items-center justify-center"><Loader2 className="h-6 w-6 animate-spin text-primary" /></div>;
  return <div className="space-y-6"><div><div className="mb-1 flex items-center gap-2 text-xs font-semibold uppercase tracking-[.18em] text-primary"><Target className="h-4 w-4" /> Aquisição</div><h1 className="text-2xl font-bold">Tracking de Leads</h1><p className="mt-1 text-sm text-muted-foreground">Veja de onde cada lead veio e devolva as conversões para suas campanhas.</p></div>
    <div className="grid gap-4 sm:grid-cols-3"><Metric label="Leads rastreados" value={leads.length} icon={MousePointerClick}/><Metric label="Convertidos/qualificados" value={converted} icon={CheckCircle2}/><Metric label="Taxa de conversão" value={`${leads.length ? Math.round(converted / leads.length * 100) : 0}%`} icon={BarChart3}/></div>
    <div className="grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><section className="rounded-2xl border bg-card p-5"><h2 className="font-semibold">Origem dos leads</h2><div className="mt-4 space-y-3">{Object.keys(grouped).length ? Object.entries(grouped).sort((a,b)=>b[1]-a[1]).map(([source,count]) => <div key={source}><div className="mb-1 flex justify-between text-sm"><span>{LABELS[source] || source}</span><strong>{count}</strong></div><div className="h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{ width: `${Math.max(5, count / leads.length * 100)}%` }} /></div></div>) : <p className="text-sm text-muted-foreground">Os novos leads aparecerão aqui com suas UTMs e origem.</p>}</div></section>
    <section className="rounded-2xl border bg-card p-5"><h2 className="font-semibold">Últimos leads</h2><div className="mt-3 divide-y divide-border">{leads.slice(0,6).map(lead => <div key={lead.id} className="flex items-center justify-between gap-3 py-3"><div className="min-w-0"><p className="truncate text-sm font-medium">{lead.name || lead.phone}</p><p className="text-xs text-muted-foreground">{LABELS[lead.lead_source] || lead.lead_source} · {lead.utm_campaign || "Sem campanha"}</p></div><select aria-label="Status da conversão" value={lead.conversion_status} onChange={e=>void convert(lead.id,e.target.value)} className="h-8 rounded-lg border bg-background px-2 text-xs"><option value="lead">Lead</option><option value="qualified_lead">Qualificado</option><option value="opportunity">Oportunidade</option><option value="customer">Cliente</option><option value="lost">Perdido</option></select></div>)}</div></section></div>
    <section className="rounded-2xl border bg-card p-5"><div><h2 className="font-semibold">Devolver conversões aos anúncios</h2><p className="text-xs text-muted-foreground">Tokens são criptografados. O lead precisa chegar com click ID/UTM para atribuição correta.</p></div><div className="mt-5 grid gap-5 lg:grid-cols-2"><Channel title="Meta Conversions API" enabled={settings.meta_enabled} onEnabled={v=>set("meta_enabled",v)} idLabel="Pixel ID" idValue={settings.meta_pixel_id} onId={v=>set("meta_pixel_id",v)} token={settings.meta_token} onToken={v=>set("meta_token",v)} saved={settings.has_meta_token} disabled={!canEdit}/><div className="space-y-3 rounded-xl border p-4"><div className="flex justify-between"><strong>Google Ads Offline Conversions</strong><Switch checked={settings.google_enabled} onCheckedChange={v=>set("google_enabled",v)} disabled={!canEdit}/></div><div><Label>Customer ID</Label><Input value={settings.google_customer_id} onChange={e=>set("google_customer_id",e.target.value)} disabled={!canEdit} className="mt-1" placeholder="123-456-7890"/></div><div><Label>Conversion Action</Label><Input value={settings.google_conversion_action} onChange={e=>set("google_conversion_action",e.target.value)} disabled={!canEdit} className="mt-1"/></div><div><Label>Access token</Label><Input type="password" value={settings.google_token} onChange={e=>set("google_token",e.target.value)} disabled={!canEdit} className="mt-1" placeholder={settings.has_google_token ? "Token salvo ••••••••" : "Cole o token"}/></div></div></div><div className="mt-5 flex justify-end"><Button onClick={save} disabled={!canEdit || saving}><Save className="h-4 w-4" />{saving ? "Salvando..." : "Salvar tracking"}</Button></div></section>
  </div>;
}
function Metric({ label, value, icon: Icon }: { label: string; value: string | number; icon: typeof Target }) { return <div className="rounded-2xl border bg-card p-5"><Icon className="h-5 w-5 text-primary"/><p className="mt-3 text-2xl font-bold">{value}</p><p className="text-xs text-muted-foreground">{label}</p></div>; }
function Channel({ title, enabled, onEnabled, idLabel, idValue, onId, token, onToken, saved, disabled }: { title:string; enabled:boolean; onEnabled:(v:boolean)=>void; idLabel:string; idValue:string; onId:(v:string)=>void; token:string; onToken:(v:string)=>void; saved:boolean; disabled:boolean }) { return <div className="space-y-3 rounded-xl border p-4"><div className="flex justify-between"><strong>{title}</strong><Switch checked={enabled} onCheckedChange={onEnabled} disabled={disabled}/></div><div><Label>{idLabel}</Label><Input value={idValue} onChange={e=>onId(e.target.value)} disabled={disabled} className="mt-1"/></div><div><Label>Access token</Label><Input type="password" value={token} onChange={e=>onToken(e.target.value)} disabled={disabled} className="mt-1" placeholder={saved ? "Token salvo ••••••••" : "Cole o token"}/></div></div>; }
